---
# tasks file for services_config
- name: Create Gunicorn systemd service
  ansible.builtin.template:
    src: gunicorn.service.j2
    dest: /etc/systemd/system/gunicorn.service
    owner: root
    group: root
    mode: '0644'
  become: yes
  when: inventory_hostname in groups['main']

- name: Create Celery Beat systemd service
  ansible.builtin.template:
    src: celery-beat.service.j2
    dest: /etc/systemd/system/celery-beat.service
    owner: root
    group: root
    mode: '0644'
  become: yes
  when: inventory_hostname in groups['main']

- name: Create Celery Worker systemd service
  ansible.builtin.template:
    src: celery-worker.service.j2
    dest: /etc/systemd/system/celery-worker.service
    owner: root
    group: root
    mode: '0644'
  become: yes
  # when: inventory_hostname in groups['nodes']

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes
  become: yes

- name: Enable and start Gunicorn
  ansible.builtin.systemd:
    name: gunicorn
    enabled: yes
    state: started
  become: yes
  when: inventory_hostname in groups['main']

- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes
  become: yes
  when: inventory_hostname in groups['main']

- name: Configure Nginx
  template:
    src: nginx_django.conf.j2
    dest: /etc/nginx/sites-available/django
  become: yes
  when: inventory_hostname in groups['main']
  notify: Restart Nginx

- name: Enable Nginx site
  file:
    src: /etc/nginx/sites-available/django
    dest: /etc/nginx/sites-enabled/default
    state: link
  become: yes
  when: inventory_hostname in groups['main']
  notify: Restart Nginx

- name: Enable and start Nginx
  ansible.builtin.systemd:
    name: nginx
    enabled: yes
    state: started
  become: yes
  when: inventory_hostname in groups['main']

- name: Enable and start Celery Beat
  ansible.builtin.systemd:
    name: celery-beat
    enabled: yes
    state: started
  become: yes
  when: inventory_hostname in groups['main']

- name: Enable and start Celery Worker
  ansible.builtin.systemd:
    name: celery-worker
    enabled: yes
    state: started
  become: yes