services:
  timescaledb:
    # hub.docker.com
    image: timescale/timescaledb:latest-pg16
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database
    ports:
      - "5555:5432" # localhost:5432
    volumes:
      - timescale_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  timescale_data: