services:
  redis-db:
    networks:
      - cfe
    image: redis:latest
    ports:
      - "6555:6379"
    volumes:
      - redis_data:/data
  timescaledb:
    networks:
      - cfe
    # hub.docker.com
    image: timescale/timescaledb:latest-pg16
    # environment:
    #   POSTGRES_USER: your_username
    #   POSTGRES_PASSWORD: your_password
    #   POSTGRES_DB: your_database
    env_file:
      - .env.db
    ports:
      - "5555:5432" # localhost:5432
    volumes:
      - timescale_data:/var/lib/postgresql/data
    restart: unless-stopped
  web:
    networks:
      - cfe
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ID=0
      - PORT=8088
    env_file:
      - .env.web-container
    ports:
      - "8088:8088"

volumes:
  redis_data:
  timescale_data:

networks:
  cfe: