---
- name: Deploy Django project
  hosts: all
  vars:
    celery_user: "celery"
    celery_group: "celery"
  roles:
    - clone_repo
    - services_config
  tasks:
    - name: Install Redis CLI
      apt:
        name: redis-tools
        state: present
        update_cache: yes
      become: yes

- name: Deploy Redis
  hosts: main
  roles:
    - redis